name: Frontend tests

on:
  push:
    branches: ["bemästra"]
  pull_request:
    branches: ["bemästra"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

       - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install pytest pytest-bdd pytest-playwright
          playwright install

      - name: Run tests (headless)
        run: |
          source .venv/bin/activate
          pytest -s
